Fixed

diff --git a/.github/workflows/linux_e_manual.yml b/.github/workflows/linux_e_manual.yml
--- a/.github/workflows/linux_e_manual.yml
+++ b/.github/workflows/linux_e_manual.yml
@@ -28,7 +28,7 @@ jobs:
           sudo add-apt-repository "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
           sudo apt update
           sudo apt-get install -qq mesa-vulkan-drivers
-          
+
           sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
             libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm \
             xvfb wget2 unzip scons git
@@ -72,7 +72,7 @@ jobs:
 
       - name: Create Project
         run: |
-         DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san ManualTesting.tscn --headless || true
+          DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san ManualTesting.tscn --headless || true
 
       - name: Configure Project Data
         run: |
@@ -85,7 +85,7 @@ jobs:
 
       - name: Run project Vulkan
         run: |
-         DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt >> project_results.txt
 
       - name: Run reproducer
@@ -94,7 +94,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+            UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
@@ -123,7 +123,7 @@ jobs:
       - name: Run project GLES3
         run: |
           for i in {0..50}; do echo "" >> project_results.txt; done;
-         DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --rendering-driver opengl3 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --rendering-driver opengl3 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt >> project_results.txt
 
       - name: Run reproducer
@@ -132,7 +132,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --rendering-driver opengl3 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+            UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --rendering-driver opengl3 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
@@ -161,7 +161,7 @@ jobs:
       - name: Run project Headless
         run: |
           for i in {0..50}; do echo "" >> project_results.txt; done;
-         DRI_PRIME=0 ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          DRI_PRIME=0 ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt >> project_results.txt
 
       - name: Run reproducer
@@ -170,7 +170,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+            UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
@@ -201,7 +201,7 @@ jobs:
           echo "echo "[rendering]" >> project.godot"
           echo "echo "vulkan/rendering/back_end=1" >> project.godot"
           for i in {0..50}; do echo "" >> project_results.txt; done;
-         DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt >> project_results.txt
 
       - name: Run reproducer
@@ -210,7 +210,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+            UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
diff --git a/.github/workflows/linux_godot4_Vulkan_Minimal.yml b/.github/workflows/linux_godot4_Vulkan_Minimal.yml
--- a/.github/workflows/linux_godot4_Vulkan_Minimal.yml
+++ b/.github/workflows/linux_godot4_Vulkan_Minimal.yml
@@ -32,7 +32,7 @@ jobs:
           sudo add-apt-repository "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
           sudo apt update
           sudo apt-get install -qq mesa-vulkan-drivers
-          
+
           sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
             libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm \
             xvfb wget2 unzip scons git
@@ -71,7 +71,7 @@ jobs:
 
       - name: Open Godot Editor
         run: |
-         UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san -e --quit --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san -e --quit --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt > editor_results.txt
 
       - name: Store editor results
@@ -98,7 +98,7 @@ jobs:
         run: |
           for i in {0..50}; do echo "" >> project_results.txt; done;
           echo "======================================== SimpleThings" 2>&1 | tee sanitizers_log.txt
-         UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 660 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SimpleThings.tscn 300 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 660 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SimpleThings.tscn 300 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 200 sanitizers_log.txt >> project_results.txt
 
           if [ -f "results.txt" ]; then
@@ -145,7 +145,7 @@ jobs:
         run: |
           for i in {0..50}; do echo "" >> project_results.txt; done;
           echo "======================================== Variant Tester" 2>&1 | tee sanitizers_log.txt
-         UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san VariantTester.tscn 600 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san VariantTester.tscn 600 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 200 sanitizers_log.txt >> project_results.txt
 
           if [ -f "results.txt" ]; then
@@ -192,7 +192,7 @@ jobs:
         run: |
           for i in {0..50}; do echo "" >> project_results.txt; done;
           echo "======================================== GDScript Fuzzer" 2>&1 | tee sanitizers_log.txt
-         UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san GDScriptCreator.tscn 600 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san GDScriptCreator.tscn 600 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 200 sanitizers_log.txt >> project_results.txt
 
           if [ -f "results.txt" ]; then
@@ -239,7 +239,7 @@ jobs:
         run: |
           for i in {0..50}; do echo "" >> project_results.txt; done;
           echo "======================================== Default" 2>&1 | tee sanitizers_log.txt
-         UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 1260 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san FunctionExecutor.tscn 900 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 1260 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san FunctionExecutor.tscn 900 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 200 sanitizers_log.txt >> project_results.txt
 
           if [ -f "results.txt" ]; then
@@ -278,7 +278,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 .  --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+            UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 .  --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
diff --git a/.github/workflows/linux_godot4_headless_repeater.yml b/.github/workflows/linux_godot4_headless_repeater.yml
--- a/.github/workflows/linux_godot4_headless_repeater.yml
+++ b/.github/workflows/linux_godot4_headless_repeater.yml
@@ -32,7 +32,7 @@ jobs:
           sudo add-apt-repository "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
           sudo apt update
           sudo apt-get install -qq mesa-vulkan-drivers
-          
+
           sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
             libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm \
             xvfb wget2 unzip scons git
@@ -65,7 +65,7 @@ jobs:
 
       - name: Open Godot Editor
         run: |
-          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san -e --quit --audio-driver Dummy --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san -e --quit --audio-driver Dummy --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt > editor_results.txt
 
       - name: Store editor results
@@ -93,14 +93,14 @@ jobs:
           for iteration in {1..240}; do
             for i in {0..50}; do echo "" >> project_results.txt; done;
             echo "======================================== Default" 2>&1 | tee sanitizers_log.txt
-            UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san FunctionExecutor.tscn 0 --audio-driver Dummy --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+             UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san FunctionExecutor.tscn 0 --audio-driver Dummy --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
             tail -n 200 sanitizers_log.txt >> project_results.txt
-          
+
             if [ -d "CRASH_INFO" ]; then
               echo "CRASH_INFO folder found. Exiting loop."
               break
             fi
-          
+
             if [ -f "results.txt" ]; then
               if [ -f "results_end.txt" ]; then
                 for i in {0..50}; do echo "" >> t.txt; done;
@@ -110,14 +110,14 @@ jobs:
                 cp "results.txt" "results_end.txt"
               fi
             fi
-          
+
             echo "extends Node" > temp.txt
             echo "func _process(delta):" >> temp.txt
             if [ -f results.txt ]; then
               cat temp.txt results.txt > Node.gd.test || true
-             UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+              UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
             fi
-          done
+           Done
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
