22.04

diff --git a/.github/workflows/linux_godot4_GL3_Normal.yml b/.github/workflows/linux_godot4_GL3_Normal.yml
--- a/.github/workflows/linux_godot4_GL3_Normal.yml
+++ b/.github/workflows/linux_godot4_GL3_Normal.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   linux-sanitizer:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     name: Editor and project
 
     steps:
@@ -130,10 +130,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -197,10 +199,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -264,10 +268,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -326,10 +332,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -393,10 +401,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -459,10 +469,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -525,10 +537,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -591,10 +605,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -656,10 +672,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -723,10 +741,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -792,10 +812,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -859,10 +881,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -928,10 +952,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -998,10 +1024,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --rendering-driver opengl3 --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
diff --git a/.github/workflows/linux_godot4_Vulkan_Minimal.yml b/.github/workflows/linux_godot4_Vulkan_Minimal.yml
--- a/.github/workflows/linux_godot4_Vulkan_Minimal.yml
+++ b/.github/workflows/linux_godot4_Vulkan_Minimal.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   linux-sanitizer:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     name: Editor and project
 
     steps:
@@ -124,10 +124,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 .  --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 .  --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -186,10 +188,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 .  --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 .  --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -248,10 +252,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 .  --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 .  --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -310,10 +316,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 .  --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 .  --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
diff --git a/.github/workflows/linux_godot4_headless_Normal.yml b/.github/workflows/linux_godot4_headless_Normal.yml
--- a/.github/workflows/linux_godot4_headless_Normal.yml
+++ b/.github/workflows/linux_godot4_headless_Normal.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   linux-sanitizer:
-    runs-on: "ubuntu-20.04"
+    runs-on: "ubuntu-22.04"
     name: Editor and project
 
     steps:
@@ -124,10 +124,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -191,10 +193,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -258,10 +262,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -320,10 +326,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -387,10 +395,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -453,10 +463,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -519,10 +531,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -585,10 +599,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -650,10 +666,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -717,10 +735,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -786,10 +806,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -853,10 +875,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -922,10 +946,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
@@ -992,10 +1018,12 @@ jobs:
         run: |
           echo "extends Node" > temp.txt
           echo "func _process(delta):" >> temp.txt
-          cat temp.txt results.txt > Node.gd.test
-          wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
-          chmod +x ./reproducer
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            wget https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_0.1.1 -O reproducer
+            chmod +x ./reproducer
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0  ./reproducer godot.linuxbsd.editor.dev.x86_64.san 40 . --headless --audio-driver Dummy || echo "ERROR: REPRODUCER FAILURE"
+          fi
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
