One by one

diff --git a/.github/workflows/linux_godot4_headless_repeater.yml b/.github/workflows/linux_godot4_headless_repeater.yml
--- a/.github/workflows/linux_godot4_headless_repeater.yml
+++ b/.github/workflows/linux_godot4_headless_repeater.yml
@@ -92,48 +92,46 @@ jobs:
 
       - name: Run Project SimpleThings
         run: |
-          for i in {0..50}; do echo "" >> project_results.txt; done;
-          echo "======================================== Default" 2>&1 | tee sanitizers_log.txt
-          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san FunctionExecutor.tscn 0 --audio-driver Dummy --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
-          tail -n 200 sanitizers_log.txt >> project_results.txt
-
-          if [ -f "results.txt" ]; then
-              if [ -f "results_end.txt" ]; then
-                  for i in {0..50}; do echo "" >> t.txt; done;
-                  cat "results.txt" "t.txt" "results_end.txt" > "temp.txt"
-                  mv "temp.txt" "results_end.txt"
-              else
-                  cp "results.txt" "results_end.txt"
-              fi
-          fi
+          for iteration in {1..20}; do
+            for i in {0..50}; do echo "" >> project_results.txt; done;
+            echo "======================================== Default" 2>&1 | tee sanitizers_log.txt
+            UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san FunctionExecutor.tscn 0 --audio-driver Dummy --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+            tail -n 200 sanitizers_log.txt >> project_results.txt
           
-          echo "extends Node" > temp.txt
-          echo "func _process(delta):" >> temp.txt
-          if [ -f results.txt ]; then
-            cat temp.txt results.txt > Node.gd.test || true
-            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
-          fi
-
-      - name: Run reproducer
-        run: |
-          echo "extends Node" > temp.txt
-          echo "func _process(delta):" >> temp.txt
-          if [ -f results.txt ]; then
-            cat temp.txt results.txt > Node.gd.test || true
-            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
-          fi
+            if [ -d "CRASH_INFO" ]; then
+              echo "CRASH_INFO folder found. Exiting loop."
+              break
+            fi
+          
+            if [ -f "results.txt" ]; then
+              if [ -f "results_end.txt" ]; then
+                for i in {0..50}; do echo "" >> t.txt; done;
+                cat "results.txt" "t.txt" "results_end.txt" > "temp.txt"
+                mv "temp.txt" "results_end.txt"
+              else
+                cp "results.txt" "results_end.txt"
+              fi
+            fi
+          
+            echo "extends Node" > temp.txt
+            echo "func _process(delta):" >> temp.txt
+            if [ -f results.txt ]; then
+              cat temp.txt results.txt > Node.gd.test || true
+              VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+            fi
+          done
 
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_4_headless_normal_one_by_one_parent_add_to_tree_maximum_tested_85
+          name: reproducer_4_headless
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
       - name: Store report
         uses: actions/upload-artifact@v3
         with:
-          name: report_reproducer_4_headless_normal_one_by_one_parent_add_to_tree_maximum_tested_85
+          name: report_reproducer_4_headless
           path: CRASH_INFO
           if-no-files-found: ignore
 
