Lavapipe

diff --git a/.github/workflows/linux_e_manual.yml b/.github/workflows/linux_e_manual.yml
--- a/.github/workflows/linux_e_manual.yml
+++ b/.github/workflows/linux_e_manual.yml
@@ -20,9 +20,15 @@ jobs:
           sudo cp -f misc/ci/sources.list /etc/apt/sources.list
           sudo apt-get update
 
-      # Install all packages (except scons)
+      # Install all packages (except scons) - also installs updated mesa drivers
       - name: Configure dependencies
         run: |
+          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
+          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB8B81E14DA65431D7504EA8F63F0F2B90935439
+          sudo add-apt-repository "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
+          sudo apt update
+          sudo apt-get install -qq mesa-vulkan-drivers
+          
           sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
             libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm \
             xvfb wget2 unzip scons git
@@ -56,14 +62,6 @@ jobs:
         run: |
           cp project.godot project.godot.old
 
-      # Download, unzip and setup SwiftShader library
-      - name: Download SwiftShader
-        run: |
-          wget https://github.com/qarmin/gtk_library_store/releases/download/3.24.0/swiftshader3.zip
-          unzip swiftshader3.zip
-          rm swiftshader3.zip
-          curr="$(pwd)/libvk_swiftshader.so"
-          sed -i "s|PATH_TO_CHANGE|$curr|" vk_swiftshader_icd.json
 
       - name: Configure Project Data
         run: |
@@ -74,7 +72,7 @@ jobs:
 
       - name: Create Project
         run: |
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san ManualTesting.tscn --headless || true
+         DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san ManualTesting.tscn --headless || true
 
       - name: Configure Project Data
         run: |
@@ -87,7 +85,7 @@ jobs:
 
       - name: Run project Vulkan
         run: |
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+         DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt >> project_results.txt
 
       - name: Run reproducer
@@ -96,7 +94,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
@@ -125,7 +123,7 @@ jobs:
       - name: Run project GLES3
         run: |
           for i in {0..50}; do echo "" >> project_results.txt; done;
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --rendering-driver opengl3 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+         DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --rendering-driver opengl3 --audio-driver Dummy  --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt >> project_results.txt
 
       - name: Run reproducer
@@ -134,7 +132,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --rendering-driver opengl3 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --rendering-driver opengl3 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
@@ -163,7 +161,7 @@ jobs:
       - name: Run project Headless
         run: |
           for i in {0..50}; do echo "" >> project_results.txt; done;
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json DRI_PRIME=0 ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+         DRI_PRIME=0 ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --headless --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt >> project_results.txt
 
       - name: Run reproducer
@@ -172,7 +170,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
@@ -203,7 +201,7 @@ jobs:
           echo "echo "[rendering]" >> project.godot"
           echo "echo "vulkan/rendering/back_end=1" >> project.godot"
           for i in {0..50}; do echo "" >> project_results.txt; done;
-          VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+         DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san SingletonTesting.tscn 1000 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
           tail -n 300 sanitizers_log.txt >> project_results.txt
 
       - name: Run reproducer
@@ -212,7 +210,7 @@ jobs:
           echo "func _process(delta):" >> temp.txt
           if [ -f results.txt ]; then
             cat temp.txt results.txt > Node.gd.test || true
-            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+           UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
           fi
 
       - name: Store reproducer
diff --git a/.github/workflows/linux_godot4_headless_repeater.yml b/.github/workflows/linux_godot4_headless_repeater.yml
--- a/.github/workflows/linux_godot4_headless_repeater.yml
+++ b/.github/workflows/linux_godot4_headless_repeater.yml
@@ -24,9 +24,15 @@ jobs:
           sudo cp -f misc/ci/sources.list /etc/apt/sources.list
           sudo apt-get update
 
-      # Install all packages (except scons)
+      # Install all packages (except scons) - also installs updated mesa drivers
       - name: Configure dependencies
         run: |
+          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
+          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB8B81E14DA65431D7504EA8F63F0F2B90935439
+          sudo add-apt-repository "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
+          sudo apt update
+          sudo apt-get install -qq mesa-vulkan-drivers
+          
           sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
             libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm \
             xvfb wget2 unzip scons git
@@ -51,14 +57,6 @@ jobs:
           cd ../
           rm -rf godot
 
-      # Download, unzip and setup SwiftShader library
-      - name: Download SwiftShader
-        run: |
-          wget -nv https://github.com/qarmin/gtk_library_store/releases/download/3.24.0/swiftshader3.zip
-          unzip swiftshader3.zip
-          rm swiftshader3.zip
-          curr="$(pwd)/libvk_swiftshader.so"
-          sed -i "s|PATH_TO_CHANGE|$curr|" vk_swiftshader_icd.json
 
       # Make backup of project.godot
       - name: Backup project.godot
@@ -117,7 +115,7 @@ jobs:
             echo "func _process(delta):" >> temp.txt
             if [ -f results.txt ]; then
               cat temp.txt results.txt > Node.gd.test || true
-              VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+             UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --headless --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
             fi
           done
 
