Slow x2 + bake

diff --git a/.github/workflows/linux_godot3.x_GLES2_Normal.yml b/.github/workflows/linux_godot3.x_GLES2_Normal.yml
--- a/.github/workflows/linux_godot3.x_GLES2_Normal.yml
+++ b/.github/workflows/linux_godot3.x_GLES2_Normal.yml
@@ -5,6 +5,10 @@ on:
   schedule:
     - cron: '0 0 * * *'
 
+env:
+  GODOT_BASE_BRANCH: 3.x
+  SCONS_CACHE_LIMIT: 4096
+
 jobs:
   linux-sanitizer:
     runs-on: "ubuntu-22.04"
@@ -535,7 +539,7 @@ jobs:
           echo "" > settings.txt
           cp project.godot.old project.godot
 
-          echo "used_number: 10" >> settings.txt
+          echo "used_number: 20" >> settings.txt
           echo "use_parent_methods: true" >> settings.txt
           echo "test_one_class_multiple_times: true" >> settings.txt
 
@@ -601,6 +605,73 @@ jobs:
           echo "" > settings.txt
           cp project.godot.old project.godot
 
+          echo "used_number: 8" >> settings.txt
+          echo "add_to_tree: true" >> settings.txt
+          echo "use_parent_methods: true" >> settings.txt
+          echo "test_one_class_multiple_times: true" >> settings.txt
+
+      - name: Run Project Small Numbers | Parent | One by One | Add to tree
+        run: |
+          for i in {0..50}; do echo "" >> project_results.txt; done;
+          echo "======================================== Small Numbers | Parent | One by One | Add to tree" 2>&1 | tee sanitizers_log.txt
+          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.x11.tools.64s FunctionExecutor.tscn 600 --audio-driver Dummy --video-driver GLES2 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          tail -n 200 sanitizers_log.txt >> project_results.txt
+
+          if [ -f "results.txt" ]; then
+              if [ -f "results_end.txt" ]; then
+                  for i in {0..50}; do echo "" >> t.txt; done;
+                  cat "results.txt" "t.txt" "results_end.txt" > "temp.txt"
+                  mv "temp.txt" "results_end.txt"
+              else
+                  cp "results.txt" "results_end.txt"
+              fi
+          fi
+
+          if [ -f "memory_usage.txt" ]; then
+              if [ -f "memory_usage_end.txt" ]; then
+                  for i in {0..50}; do echo "" >> t.txt; done;
+                  cat "memory_usage.txt" "t.txt" "memory_usage_end.txt" > "temp.txt"
+                  mv "temp.txt" "memory_usage_end.txt"
+              else
+                  cp "memory_usage.txt" "memory_usage_end.txt"
+              fi
+          fi
+
+          if [ -f "timer.txt" ]; then
+              if [ -f "timer_end.txt" ]; then
+                  for i in {0..50}; do echo "" >> t.txt; done;
+                  cat "timer.txt" "t.txt" "timer_end.txt" > "temp.txt"
+                  mv "temp.txt" "timer_end.txt"
+              else
+                  cp "timer.txt" "timer_end.txt"
+              fi
+          fi
+
+      - name: Run reproducer
+        run: |
+          echo "extends Node" > temp.txt
+          echo "func _process(delta):" >> temp.txt
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.x11.tools.64s 60_50 . --video-driver GLES2 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+          fi
+
+      - name: Store reproducer
+        uses: actions/upload-artifact@v3
+        with:
+          name: reproducer_3_x_gles2_normal_small_numbers_parent_one_by_one_add_to_tree_9
+          path: crash_reproduce.gd
+          if-no-files-found: ignore
+
+      - name: Configure Project Data
+        run: |
+          rm timer.txt || true
+          rm memory_usage.txt || true
+          rm results.txt || true
+          rm crash_reproduce.gd || true
+          echo "" > settings.txt
+          cp project.godot.old project.godot
+
           echo "add_arguments_to_tree: true" >> settings.txt
           echo "delay_removing_added_arguments_to_next_frame: true" >> settings.txt
 
@@ -653,7 +724,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles2_normal_add_arguments_to_tree_delaying_9
+          name: reproducer_3_x_gles2_normal_add_arguments_to_tree_delaying_10
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -720,7 +791,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles2_normal_one_by_one,_very_big_amount_of_functions_10
+          name: reproducer_3_x_gles2_normal_one_by_one,_very_big_amount_of_functions_11
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -789,7 +860,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles2_normal_one_by_one,_very_big_amount_of_functions,_add_to_tree_11
+          name: reproducer_3_x_gles2_normal_one_by_one,_very_big_amount_of_functions,_add_to_tree_12
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -856,7 +927,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles2_normal_multiple_classes,_very_big_amount_of_functions_12
+          name: reproducer_3_x_gles2_normal_multiple_classes,_very_big_amount_of_functions_13
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -927,7 +998,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles2_normal_multithread_parent_maximum_tested_13
+          name: reproducer_3_x_gles2_normal_multithread_parent_maximum_tested_14
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -999,7 +1070,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles2_normal_multithread_add_parent_maximum_tested_14
+          name: reproducer_3_x_gles2_normal_multithread_add_parent_maximum_tested_15
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
diff --git a/.github/workflows/linux_godot3.x_GLES3_Normal.yml b/.github/workflows/linux_godot3.x_GLES3_Normal.yml
--- a/.github/workflows/linux_godot3.x_GLES3_Normal.yml
+++ b/.github/workflows/linux_godot3.x_GLES3_Normal.yml
@@ -5,6 +5,10 @@ on:
   schedule:
     - cron: '0 0 * * *'
 
+env:
+  GODOT_BASE_BRANCH: 3.x
+  SCONS_CACHE_LIMIT: 4096
+
 jobs:
   linux-sanitizer:
     runs-on: "ubuntu-22.04"
@@ -194,7 +198,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_one_by_one_parent_add_to_tree_maximum_tested_20
+          name: reproducer_3_x_gles3_normal_one_by_one_parent_add_to_tree_maximum_tested_21
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -261,7 +265,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_parent_add_to_tree_maximum_tested_max_random_21
+          name: reproducer_3_x_gles3_normal_parent_add_to_tree_maximum_tested_max_random_22
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -323,7 +327,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_default_22
+          name: reproducer_3_x_gles3_normal_default_23
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -390,7 +394,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_delaying_parent_add_to_tree_maximum_tested_23
+          name: reproducer_3_x_gles3_normal_delaying_parent_add_to_tree_maximum_tested_24
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -456,7 +460,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_delaying_one_by_one_parent_24
+          name: reproducer_3_x_gles3_normal_delaying_one_by_one_parent_25
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -522,7 +526,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_big_numbers_parent_one_by_one_25
+          name: reproducer_3_x_gles3_normal_big_numbers_parent_one_by_one_26
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -535,7 +539,7 @@ jobs:
           echo "" > settings.txt
           cp project.godot.old project.godot
 
-          echo "used_number: 10" >> settings.txt
+          echo "used_number: 20" >> settings.txt
           echo "use_parent_methods: true" >> settings.txt
           echo "test_one_class_multiple_times: true" >> settings.txt
 
@@ -588,7 +592,74 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_small_numbers_parent_one_by_one_26
+          name: reproducer_3_x_gles3_normal_small_numbers_parent_one_by_one_27
+          path: crash_reproduce.gd
+          if-no-files-found: ignore
+
+      - name: Configure Project Data
+        run: |
+          rm timer.txt || true
+          rm memory_usage.txt || true
+          rm results.txt || true
+          rm crash_reproduce.gd || true
+          echo "" > settings.txt
+          cp project.godot.old project.godot
+
+          echo "used_number: 8" >> settings.txt
+          echo "add_to_tree: true" >> settings.txt
+          echo "use_parent_methods: true" >> settings.txt
+          echo "test_one_class_multiple_times: true" >> settings.txt
+
+      - name: Run Project Small Numbers | Parent | One by One | Add to tree
+        run: |
+          for i in {0..50}; do echo "" >> project_results.txt; done;
+          echo "======================================== Small Numbers | Parent | One by One | Add to tree" 2>&1 | tee sanitizers_log.txt
+          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.x11.tools.64s FunctionExecutor.tscn 600 --audio-driver Dummy --video-driver GLES3 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
+          tail -n 200 sanitizers_log.txt >> project_results.txt
+
+          if [ -f "results.txt" ]; then
+              if [ -f "results_end.txt" ]; then
+                  for i in {0..50}; do echo "" >> t.txt; done;
+                  cat "results.txt" "t.txt" "results_end.txt" > "temp.txt"
+                  mv "temp.txt" "results_end.txt"
+              else
+                  cp "results.txt" "results_end.txt"
+              fi
+          fi
+
+          if [ -f "memory_usage.txt" ]; then
+              if [ -f "memory_usage_end.txt" ]; then
+                  for i in {0..50}; do echo "" >> t.txt; done;
+                  cat "memory_usage.txt" "t.txt" "memory_usage_end.txt" > "temp.txt"
+                  mv "temp.txt" "memory_usage_end.txt"
+              else
+                  cp "memory_usage.txt" "memory_usage_end.txt"
+              fi
+          fi
+
+          if [ -f "timer.txt" ]; then
+              if [ -f "timer_end.txt" ]; then
+                  for i in {0..50}; do echo "" >> t.txt; done;
+                  cat "timer.txt" "t.txt" "timer_end.txt" > "temp.txt"
+                  mv "temp.txt" "timer_end.txt"
+              else
+                  cp "timer.txt" "timer_end.txt"
+              fi
+          fi
+
+      - name: Run reproducer
+        run: |
+          echo "extends Node" > temp.txt
+          echo "func _process(delta):" >> temp.txt
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.x11.tools.64s 60_50 . --video-driver GLES3 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+          fi
+
+      - name: Store reproducer
+        uses: actions/upload-artifact@v3
+        with:
+          name: reproducer_3_x_gles3_normal_small_numbers_parent_one_by_one_add_to_tree_28
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -653,7 +724,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_add_arguments_to_tree_delaying_27
+          name: reproducer_3_x_gles3_normal_add_arguments_to_tree_delaying_29
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -720,7 +791,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_one_by_one,_very_big_amount_of_functions_28
+          name: reproducer_3_x_gles3_normal_one_by_one,_very_big_amount_of_functions_30
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -789,7 +860,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_one_by_one,_very_big_amount_of_functions,_add_to_tree_29
+          name: reproducer_3_x_gles3_normal_one_by_one,_very_big_amount_of_functions,_add_to_tree_31
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -856,7 +927,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_multiple_classes,_very_big_amount_of_functions_30
+          name: reproducer_3_x_gles3_normal_multiple_classes,_very_big_amount_of_functions_32
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -927,7 +998,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_multithread_parent_maximum_tested_31
+          name: reproducer_3_x_gles3_normal_multithread_parent_maximum_tested_33
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
@@ -999,7 +1070,7 @@ jobs:
       - name: Store reproducer
         uses: actions/upload-artifact@v3
         with:
-          name: reproducer_3_x_gles3_normal_multithread_add_parent_maximum_tested_32
+          name: reproducer_3_x_gles3_normal_multithread_add_parent_maximum_tested_34
           path: crash_reproduce.gd
           if-no-files-found: ignore
 
