Manual Testing

diff --git a/.github/workflows/linux_e_manual.yml b/.github/workflows/linux_e_manual.yml
--- a/.github/workflows/linux_e_manual.yml
+++ b/.github/workflows/linux_e_manual.yml
@@ -30,6 +30,15 @@ jobs:
       - name: Configure Data
         run: |
           true
+          
+      - name: Backup project.godot
+        run: |
+          cp project.godot project.godot.old
+          
+      - name: Download reproducer
+        run: |
+          wget -nv https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash -O reproducer
+          chmod +x ./reproducer
 
       - name: Download Godot(GIT)
         run: |
@@ -49,7 +58,7 @@ jobs:
       - name: Create test project
         run: |
           DRI_PRIME=0 xvfb-run ./godot.x11.tools.64s ManualTesting.tscn --audio-driver Dummy --video-driver GLES2 || true
-          
+         
       - name: Execute project 1 GLES2
         run: |
           DRI_PRIME=0 xvfb-run ./godot.x11.tools.64s SingletonTesting.tscn 1000 --audio-driver Dummy --video-driver GLES2 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
@@ -57,6 +66,31 @@ jobs:
           for i in {0..50}; do echo "" >> run_results.txt; done;
           tail -n 300 sanitizers_log.txt >> project_results.txt
           cat results.txt >> run_results.txt
+          
+      - name: Configure Project Data
+        run: |
+          rm timer.txt || true
+          rm memory_usage.txt || true
+          rm results.txt || true
+          rm crash_reproduce.gd || true
+          echo "" > settings.txt
+          cp project.godot.old project.godot
+
+      - name: Run reproducer
+        run: |
+          echo "extends Node" > temp.txt
+          echo "func _process(delta):" >> temp.txt
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.x11.tools.64s 40 . --video-driver GLES2 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+          fi
+
+      - name: Store reproducer
+        uses: actions/upload-artifact@v3
+        with:
+          name: reproducer_3_x_gles2_1
+          path: crash_reproduce.gd
+          if-no-files-found: ignore
           
       - name: Execute project 2 GLES2
         run: |
@@ -66,6 +100,31 @@ jobs:
           tail -n 300 sanitizers_log.txt >> project_results.txt
           cat results.txt >> run_results.txt
           
+      - name: Configure Project Data
+        run: |
+          rm timer.txt || true
+          rm memory_usage.txt || true
+          rm results.txt || true
+          rm crash_reproduce.gd || true
+          echo "" > settings.txt
+          cp project.godot.old project.godot
+
+      - name: Run reproducer
+        run: |
+          echo "extends Node" > temp.txt
+          echo "func _process(delta):" >> temp.txt
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.x11.tools.64s 40 . --video-driver GLES2 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+          fi
+
+      - name: Store reproducer
+        uses: actions/upload-artifact@v3
+        with:
+          name: reproducer_3_x_gles2_2
+          path: crash_reproduce.gd
+          if-no-files-found: ignore
+          
       - name: Execute project 3 GLES2
         run: |
           DRI_PRIME=0 xvfb-run ./godot.x11.tools.64s SingletonTesting.tscn 1000 --audio-driver Dummy --video-driver GLES2 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
@@ -73,6 +132,32 @@ jobs:
           for i in {0..50}; do echo "" >> run_results.txt; done;
           tail -n 300 sanitizers_log.txt >> project_results.txt
           cat results.txt >> run_results.txt
+          
+          
+      - name: Configure Project Data
+        run: |
+          rm timer.txt || true
+          rm memory_usage.txt || true
+          rm results.txt || true
+          rm crash_reproduce.gd || true
+          echo "" > settings.txt
+          cp project.godot.old project.godot
+
+      - name: Run reproducer
+        run: |
+          echo "extends Node" > temp.txt
+          echo "func _process(delta):" >> temp.txt
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.x11.tools.64s 40 . --video-driver GLES2 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+          fi
+
+      - name: Store reproducer
+        uses: actions/upload-artifact@v3
+        with:
+          name: reproducer_3_x_gles2_3
+          path: crash_reproduce.gd
+          if-no-files-found: ignore
           
       - name: Execute project 1 GLES3
         run: |
@@ -82,6 +167,32 @@ jobs:
           tail -n 300 sanitizers_log.txt >> project_results.txt
           cat results.txt >> run_results.txt
           
+          
+      - name: Configure Project Data
+        run: |
+          rm timer.txt || true
+          rm memory_usage.txt || true
+          rm results.txt || true
+          rm crash_reproduce.gd || true
+          echo "" > settings.txt
+          cp project.godot.old project.godot
+
+      - name: Run reproducer
+        run: |
+          echo "extends Node" > temp.txt
+          echo "func _process(delta):" >> temp.txt
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.x11.tools.64s 40 . --video-driver GLES3 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+          fi
+
+      - name: Store reproducer
+        uses: actions/upload-artifact@v3
+        with:
+          name: reproducer_3_x_gles3_1
+          path: crash_reproduce.gd
+          if-no-files-found: ignore
+          
       - name: Execute project 2 GLES3
         run: |
           DRI_PRIME=0 xvfb-run ./godot.x11.tools.64s SingletonTesting.tscn 1000 --audio-driver Dummy --video-driver GLES3 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
@@ -89,6 +200,32 @@ jobs:
           for i in {0..50}; do echo "" >> run_results.txt; done;
           tail -n 300 sanitizers_log.txt >> project_results.txt
           cat results.txt >> run_results.txt
+          
+          
+      - name: Configure Project Data
+        run: |
+          rm timer.txt || true
+          rm memory_usage.txt || true
+          rm results.txt || true
+          rm crash_reproduce.gd || true
+          echo "" > settings.txt
+          cp project.godot.old project.godot
+
+      - name: Run reproducer
+        run: |
+          echo "extends Node" > temp.txt
+          echo "func _process(delta):" >> temp.txt
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.x11.tools.64s 40 . --video-driver GLES3 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+          fi
+
+      - name: Store reproducer
+        uses: actions/upload-artifact@v3
+        with:
+          name: reproducer_3_x_gles3_2
+          path: crash_reproduce.gd
+          if-no-files-found: ignore
           
       - name: Execute project 3 GLES3
         run: |
@@ -98,6 +235,32 @@ jobs:
           tail -n 300 sanitizers_log.txt >> project_results.txt
           cat results.txt >> run_results.txt
 
+          
+      - name: Configure Project Data
+        run: |
+          rm timer.txt || true
+          rm memory_usage.txt || true
+          rm results.txt || true
+          rm crash_reproduce.gd || true
+          echo "" > settings.txt
+          cp project.godot.old project.godot
+
+      - name: Run reproducer
+        run: |
+          echo "extends Node" > temp.txt
+          echo "func _process(delta):" >> temp.txt
+          if [ -f results.txt ]; then
+            cat temp.txt results.txt > Node.gd.test || true
+            VK_ICD_FILENAMES=$(pwd)/vk_swiftshader_icd.json UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.x11.tools.64s 40 . --video-driver GLES3 --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
+          fi
+
+      - name: Store reproducer
+        uses: actions/upload-artifact@v3
+        with:
+          name: reproducer_3_x_gles3_3
+          path: crash_reproduce.gd
+          if-no-files-found: ignore
+          
       - name: Store project results
         uses: actions/upload-artifact@v3
         with:
